#!/bin/sh
#
if [ "$1" != "" ]
then
	branch=$1
	export branch
fi

if [ "$branch" = "" ]
then
	branch=trunk
fi
# branch=branches/xxx

astrolib=http://svn6.assembla.com/svn/astrolib/
stsci_python=https://svn.stsci.edu/svn/ssb/stsci_python/
pyfits=http://svn6.assembla.com/svn/pyfits/
pyraf=http://svn6.assembla.com/svn/pyraf/

## list packages here in any order you like
## column 1 is the package name (that it will be installed as)
## column 2 is 'svn' for packages stored in subversion
## column 3 is the url to check out, based on $branch and repository
##	    prefixes defined above
sed -e '/^[ 	]*#/d' -e '/^$/d' << ARF
new_install         svn         $stsci_python/stsci_python/$branch/new_install

acstools	    svn		$stsci_python/stsci_python/$branch/acstools
astrolib.coords     svn		$astrolib/$branch/coords
calcos		    svn		$stsci_python/stsci_python/$branch/calcos
costools	    svn		$stsci_python/stsci_python/$branch/costools
d2to1		    svn		$stsci_python/d2to1/$branch
drizzlepac	    svn		$stsci_python/stsci_python/$branch/drizzlepac
fitsblender	    svn		$stsci_python/stsci_python/$branch/fitsblender
multidrizzle	    svn		$stsci_python/stsci_python/$branch/multidrizzle
nictools	    svn		$stsci_python/stsci_python/$branch/nictools
opuscoords	    svn		$stsci_python/stsci_python/$branch/opuscoords
pydrizzle	    svn		$stsci_python/stsci_python/$branch/pydrizzle
pyfits		    svn		$pyfits/$branch
pyraf		    svn		$pyraf/$branch
pysynphot	    svn		$astrolib/$branch/pysynphot
pywcs		    svn		$astrolib/$branch/pywcs
reftools	    svn		$stsci_python/stsci_python/$branch/reftools
sample_project	    svn		$stsci_python/sample_project/$branch
stistools	    svn		$stsci_python/stsci_python/$branch/stistools
stsci.convolve	    svn		$stsci_python/stsci_python/$branch/stsci.convolve
stsci.distutils	    svn		$stsci_python/stsci.distutils/$branch
stsci.image	    svn		$stsci_python/stsci_python/$branch/image
stsci.imagemanip    svn		$stsci_python/stsci_python/$branch/imagemanip
stsci.imagestats    svn		$stsci_python/stsci_python/$branch/imagestats
stsci.ndimage	    svn		$stsci_python/stsci_python/$branch/stsci.ndimage
stsci.numdisplay    svn		$stsci_python/stsci_python/$branch/numdisplay
stsci.sphinxext	    svn		$astrolib/$branch/stsci_sphinxext
stsci.stimage	    svn		$stsci_python/stsci_python/$branch/stimage
stsci.tools	    svn		$stsci_python/stsci_python/$branch/tools
stwcs		    svn		$stsci_python/stsci_python/$branch/stwcs
wfc3tools           svn         $stsci_python/stsci_python/$branch/wfc3tools
wfpc2tools	    svn		$stsci_python/stsci_python/$branch/wfpc2tools

ARF
