#!/bin/sh
#
if [ "$1" != "" ]
then
	branch=$1
	export branch
fi

if [ "$branch" = "" ]
then
	branch=trunk
fi
# branch=branches/xxx

astrolib=http://svn6.assembla.com/svn/astrolib/
stsci_python=https://svn.stsci.edu/svn/ssb/stsci_python/
pyfits=http://svn6.assembla.com/svn/pyfits/
pyraf=http://svn6.assembla.com/svn/pyraf/

## list packages here in any order you like
## column 1 is the package name (that it will be installed as)
## column 2 is 'svn' for packages stored in subversion
## column 3 is the url to check out, based on $branch and repository
##	    prefixes defined above
sed -e '/^[ 	]*#/d' -e '/^$/d' << ARF
new_install         svn         $stsci_python/stsci_python/$branch/new_install

d2to1		    svn		$stsci_python/d2to1/$branch
stsci.distutils	    svn		$stsci_python/stsci.distutils/$branch
pyfits		    svn		$pyfits/$branch
stsci.tools	    svn		$stsci_python/stsci_python/$branch/tools
stsci.ndimage	    svn		$stsci_python/stsci_python/$branch/stsci.ndimage
stsci.convolve	    svn		$stsci_python/stsci_python/$branch/stsci.convolve
pywcs		    svn		$astrolib/$branch/pywcs
stwcs		    svn		$stsci_python/stsci_python/$branch/stwcs
stsci.stimage	    svn		$stsci_python/stsci_python/$branch/stimage
stsci.imagestats    svn		$stsci_python/stsci_python/$branch/imagestats
stsci.imagemanip    svn		$stsci_python/stsci_python/$branch/imagemanip
stsci.image	    svn		$stsci_python/stsci_python/$branch/image
pysynphot	    svn		$astrolib/$branch/pysynphot
pydrizzle	    svn		$stsci_python/stsci_python/$branch/pydrizzle
nictools	    svn		$stsci_python/stsci_python/$branch/nictools
calcos		    svn		$stsci_python/stsci_python/$branch/calcos
astrolib.coords     svn		$astrolib/$branch/coords
wfpc2tools	    svn		$stsci_python/stsci_python/$branch/wfpc2tools
wfc3tools           svn         $stsci_python/stsci_python/$branch/wfc3tools
stsci.sphinxext	    svn		$astrolib/$branch/stsci_sphinxext
stsci.numdisplay    svn		$stsci_python/stsci_python/$branch/numdisplay
stistools	    svn		$stsci_python/stsci_python/$branch/stistools
sample_project	    svn		$stsci_python/sample_project/$branch
reftools	    svn		$stsci_python/stsci_python/$branch/reftools
pyraf		    svn		$pyraf/$branch
opuscoords	    svn		$stsci_python/stsci_python/$branch/opuscoords
multidrizzle	    svn		$stsci_python/stsci_python/$branch/multidrizzle
fitsblender	    svn		$stsci_python/stsci_python/$branch/fitsblender
drizzlepac	    svn		$stsci_python/stsci_python/$branch/drizzlepac
costools	    svn		$stsci_python/stsci_python/$branch/costools
acstools	    svn		$stsci_python/stsci_python/$branch/acstools

ARF
