#!/bin/sh
#
# We now have several svn externals.  Check that all the svn:externals came from the same branch

main_url=`svn info | grep URL: | awk '{ print $2 }' `

case "$main_url"
in
*/branches/*)
	branch=`echo $main_url | sed 's?^.*/branches/??'`
	;;
*)
	echo not on a branch
	exit 1
esac

echo ''
echo 'this branch name is '$branch
echo ''

dobranch() {
	# dobranch name
	#	name is the name of the package that is an svn external

	# arg is the name of the branch
	name=$1

	# pick the URL out of the svn:externals property
	url=` svn propget svn:externals | sed -n "/^$name/p" | awk '{ print $2 }' `

	case "$url"
	in
	*/branches/$branch)
		ok=1
		;;
	*/branches/$branch/*)
		ok=1
		;;
	*)
		echo "ERROR: $name is not from the same branch:"
		echo "       expect '$branch"
		echo "       found  '$url"
		;;
	esac

}



check_externals() {

	rm -f tmp.*

	for x in `svn propget svn:externals . | awk '{ print $1 }' `
	do
		dobranch $x
	done

}

check_externals

