#!/bin/sh

case "$0"
in 
release_tools/testenv)
	:
	;;
*)
	echo 'not invoked correctly - see release_tools/README'
	exit 1
	;;
esac

case "$PYTHONPATH" 
in 
*:*)	echo too many dirs on pythonpath - see release_tools/README
	exit 1
	;;
'')	echo pythonpath not set - see release_tools/README
	exit 1
	;;
esac

here=`pwd`

pyhome=$here/py

rm -rf $here/py $here/pyssgN

mkdir -p $pyhome/lib/python
mkdir -p $pyhome/bin

mkdir -p $here/pyssgN/lib
mkdir -p $here/pyssgN/bin

# not needed with new pyssgdev layout
# ( cd $PYTHONPATH ; tar cf - . ) | ( cd $here/pyssgN/lib ; tar xf - )

d=`which pyraf`
d=`dirname $d`

( ln -s $d/* $here/pyssgN/bin )

p="$here/py/bin $here/pyssgN/bin"

for x in `echo $PATH | sed 's/:/ /g'`
do
	case "$x"
	in
	$d) 	: ;;
	*)	p="$p $x"
		;;
	esac
done

echo setenv pyhome $pyhome
echo ''
echo setenv PYTHONPATH $pyhome/lib/python:$here/pyssgN/lib:$PYTHONPATH
echo ''
echo set path = '(' $p ')'
echo ''
echo export pyhome=$pyhome
echo ''
echo export PYTHONPATH=$pyhome/lib/python:$here/pyssgN/lib:$PYTHONPATH
echo ''
echo export PATH=`echo $p | sed 's/ /:/g'`
echo ''
echo python uninstall.py -f
echo ''
echo python setup.py install --home $here/py
echo ''

