#!/bin/sh

case "$PYTHONPATH" 
in 
*:*)	echo too many dirs on pythonpath - see release_tools/README
	exit 1
	;;
'')	echo pythonpath not set - see release_tools/README
	exit 1
	;;
esac

here=`pwd`

rm -rf $here/py $here/pyssgN

mkdir -p $here/py/lib/python
mkdir -p $here/py/bin

mkdir -p $here/pyssgN/lib
mkdir -p $here/pyssgN/bin

( cd $PYTHONPATH ; tar cf - . ) | ( cd $here/pyssgN/lib ; tar xf - )

d=`which pyraf`
d=`dirname $d`

( ln -s $d/* $here/pyssgN/bin )

p="$here/py/bin $here/pyssgN/bin"

for x in `echo $PATH | sed 's/:/ /g'`
do
	case "$x"
	in
	$d) 	: ;;
	*)	p="$p $x"
		;;
	esac
done

echo ''
echo setenv PYTHONPATH $here/py/lib/python:$here/pyssgN/lib
echo ''
echo set path = '(' $p ')'
echo ''
echo export PYTHONPATH=$here/py/lib/python:$here/pyssgN
echo ''
echo export PATH=`echo $p | sed 's/ /:/g'`
echo ''
echo python uninstall.py -f
echo ''
echo python setup.py install --home $here/py
echo ''

